service: cdarre_portfolio
image: c-darre/cdarre_portfolio

servers:
  web:
    - 152.228.235.230

proxy:
  ssl: true
  hosts:
    - cdarre.fr
    - www.cdarre.fr
  app_port: 3000
  deploy_timeout: 120

registry:
  server: ghcr.io
  username: c-darre
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - CDARRE_PORTFOLIO_DATABASE_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: cdarre_portfolio-db

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "cdarre_portfolio_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
  db:
    image: postgres:16
    host: 152.228.235.230
    env:
      clear:
        POSTGRES_USER: cdarre_portfolio
        POSTGRES_DB: cdarre_portfolio_production
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/production_init.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
